/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EventsRouteImport } from './routes/events'
import { Route as NieuwsRouteImport } from './routes/nieuws'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SocialsRouteImport } from './routes/socials'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ClubBestuurRouteImport } from './routes/club/bestuur'
import { Route as ClubGeschiedenisRouteImport } from './routes/club/geschiedenis'
import { Route as ClubMediaRouteImport } from './routes/club/media'
import { Route as ClubPrivacyRouteImport } from './routes/club/privacy'
import { Route as ClubSfeerRouteImport } from './routes/club/sfeer'
import { Route as ClubSponsorsRouteImport } from './routes/club/sponsors'
import { Route as ClubTeamsRouteImport } from './routes/club/teams'
import { Route as ClubVeldRouteImport } from './routes/club/veld'
import { Route as ClubVeldStatusRouteImport } from './routes/club/veld-status'
import { Route as ClubWaardenRouteImport } from './routes/club/waarden'
import { Route as LidmaatschapContactRouteImport } from './routes/lidmaatschap/contact'
import { Route as LidmaatschapIndoorRegistratieRouteImport } from './routes/lidmaatschap/indoor-registratie'
import { Route as LidmaatschapInfoRouteImport } from './routes/lidmaatschap/info'
import { Route as LidmaatschapRegistratieRouteImport } from './routes/lidmaatschap/registratie'
import { Route as LidmaatschapVerzekeringRouteImport } from './routes/lidmaatschap/verzekering'
import { Route as SportiefCoachesInfoRouteImport } from './routes/sportief/coaches-info'
import { Route as SportiefHockeyPrincipesRouteImport } from './routes/sportief/hockey-principes'
import { Route as SportiefHoeTeSpelenRouteImport } from './routes/sportief/hoe-te-spelen'
import { Route as SportiefIndoorHockeyRouteImport } from './routes/sportief/indoor-hockey'
import { Route as SportiefRegelsAssistentRouteImport } from './routes/sportief/regels-assistent'
import { Route as SportiefStickGidsRouteImport } from './routes/sportief/stick-gids'
import { Route as SportiefTrainingRouteImport } from './routes/sportief/training'
import { Route as VacaturesIndexRouteImport } from './routes/vacatures/index'
import { Route as VacaturesSlugRouteImport } from './routes/vacatures/$slug'
import { Route as AdminAnnouncementsIndexRouteImport } from './routes/admin/announcements/index'
import { Route as AdminAnnouncementsNewRouteImport } from './routes/admin/announcements/new'
import { Route as AdminBoardMembersIndexRouteImport } from './routes/admin/board-members/index'
import { Route as AdminBoardMembersNewRouteImport } from './routes/admin/board-members/new'
import { Route as AdminFieldClosuresIndexRouteImport } from './routes/admin/field-closures/index'
import { Route as AdminFieldClosuresNewRouteImport } from './routes/admin/field-closures/new'
import { Route as AdminSponsorsIndexRouteImport } from './routes/admin/sponsors/index'
import { Route as AdminSponsorsNewRouteImport } from './routes/admin/sponsors/new'
import { Route as AdminTeamsIndexRouteImport } from './routes/admin/teams/index'
import { Route as AdminTeamsNewRouteImport } from './routes/admin/teams/new'
import { Route as AdminVacanciesIndexRouteImport } from './routes/admin/vacancies/index'
import { Route as AdminVacanciesNewRouteImport } from './routes/admin/vacancies/new'
import { Route as SportiefRegelsIndexRouteImport } from './routes/sportief/regels/index'
import { Route as SportiefRegelsIndoorRouteImport } from './routes/sportief/regels/indoor'
import { Route as SportiefRegelsU10U12RouteImport } from './routes/sportief/regels/u10-u12'
import { Route as SportiefRegelsU14PlusRouteImport } from './routes/sportief/regels/u14-plus'
import { Route as SportiefRegelsU6U8RouteImport } from './routes/sportief/regels/u6-u8'
import { Route as SportiefRegelsU9RouteImport } from './routes/sportief/regels/u9'
import { Route as AdminAnnouncementsEditIdRouteImport } from './routes/admin/announcements/edit.$id'
import { Route as AdminBoardMembersEditIdRouteImport } from './routes/admin/board-members/edit.$id'
import { Route as AdminFieldClosuresEditIdRouteImport } from './routes/admin/field-closures/edit.$id'
import { Route as AdminSponsorsEditIdRouteImport } from './routes/admin/sponsors/edit.$id'
import { Route as AdminTeamsEditIdRouteImport } from './routes/admin/teams/edit.$id'
import { Route as AdminVacanciesEditIdRouteImport } from './routes/admin/vacancies/edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const NieuwsRoute = NieuwsRouteImport.update({
  id: '/nieuws',
  path: '/nieuws',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialsRoute = SocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubBestuurRoute = ClubBestuurRouteImport.update({
  id: '/club/bestuur',
  path: '/club/bestuur',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubGeschiedenisRoute = ClubGeschiedenisRouteImport.update({
  id: '/club/geschiedenis',
  path: '/club/geschiedenis',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubMediaRoute = ClubMediaRouteImport.update({
  id: '/club/media',
  path: '/club/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubPrivacyRoute = ClubPrivacyRouteImport.update({
  id: '/club/privacy',
  path: '/club/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubSfeerRoute = ClubSfeerRouteImport.update({
  id: '/club/sfeer',
  path: '/club/sfeer',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubSponsorsRoute = ClubSponsorsRouteImport.update({
  id: '/club/sponsors',
  path: '/club/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubTeamsRoute = ClubTeamsRouteImport.update({
  id: '/club/teams',
  path: '/club/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubVeldRoute = ClubVeldRouteImport.update({
  id: '/club/veld',
  path: '/club/veld',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubVeldStatusRoute = ClubVeldStatusRouteImport.update({
  id: '/club/veld-status',
  path: '/club/veld-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubWaardenRoute = ClubWaardenRouteImport.update({
  id: '/club/waarden',
  path: '/club/waarden',
  getParentRoute: () => rootRouteImport,
} as any)
const LidmaatschapContactRoute = LidmaatschapContactRouteImport.update({
  id: '/lidmaatschap/contact',
  path: '/lidmaatschap/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LidmaatschapIndoorRegistratieRoute =
  LidmaatschapIndoorRegistratieRouteImport.update({
    id: '/lidmaatschap/indoor-registratie',
    path: '/lidmaatschap/indoor-registratie',
    getParentRoute: () => rootRouteImport,
  } as any)
const LidmaatschapInfoRoute = LidmaatschapInfoRouteImport.update({
  id: '/lidmaatschap/info',
  path: '/lidmaatschap/info',
  getParentRoute: () => rootRouteImport,
} as any)
const LidmaatschapRegistratieRoute = LidmaatschapRegistratieRouteImport.update({
  id: '/lidmaatschap/registratie',
  path: '/lidmaatschap/registratie',
  getParentRoute: () => rootRouteImport,
} as any)
const LidmaatschapVerzekeringRoute = LidmaatschapVerzekeringRouteImport.update({
  id: '/lidmaatschap/verzekering',
  path: '/lidmaatschap/verzekering',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefCoachesInfoRoute = SportiefCoachesInfoRouteImport.update({
  id: '/sportief/coaches-info',
  path: '/sportief/coaches-info',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefHockeyPrincipesRoute = SportiefHockeyPrincipesRouteImport.update({
  id: '/sportief/hockey-principes',
  path: '/sportief/hockey-principes',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefHoeTeSpelenRoute = SportiefHoeTeSpelenRouteImport.update({
  id: '/sportief/hoe-te-spelen',
  path: '/sportief/hoe-te-spelen',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefIndoorHockeyRoute = SportiefIndoorHockeyRouteImport.update({
  id: '/sportief/indoor-hockey',
  path: '/sportief/indoor-hockey',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefRegelsAssistentRoute = SportiefRegelsAssistentRouteImport.update({
  id: '/sportief/regels-assistent',
  path: '/sportief/regels-assistent',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefStickGidsRoute = SportiefStickGidsRouteImport.update({
  id: '/sportief/stick-gids',
  path: '/sportief/stick-gids',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefTrainingRoute = SportiefTrainingRouteImport.update({
  id: '/sportief/training',
  path: '/sportief/training',
  getParentRoute: () => rootRouteImport,
} as any)
const VacaturesIndexRoute = VacaturesIndexRouteImport.update({
  id: '/vacatures/',
  path: '/vacatures/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacaturesSlugRoute = VacaturesSlugRouteImport.update({
  id: '/vacatures/$slug',
  path: '/vacatures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: '/admin/announcements/',
  path: '/admin/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsNewRoute = AdminAnnouncementsNewRouteImport.update({
  id: '/admin/announcements/new',
  path: '/admin/announcements/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoardMembersIndexRoute = AdminBoardMembersIndexRouteImport.update({
  id: '/admin/board-members/',
  path: '/admin/board-members/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoardMembersNewRoute = AdminBoardMembersNewRouteImport.update({
  id: '/admin/board-members/new',
  path: '/admin/board-members/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldClosuresIndexRoute = AdminFieldClosuresIndexRouteImport.update({
  id: '/admin/field-closures/',
  path: '/admin/field-closures/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldClosuresNewRoute = AdminFieldClosuresNewRouteImport.update({
  id: '/admin/field-closures/new',
  path: '/admin/field-closures/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsIndexRoute = AdminSponsorsIndexRouteImport.update({
  id: '/admin/sponsors/',
  path: '/admin/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsNewRoute = AdminSponsorsNewRouteImport.update({
  id: '/admin/sponsors/new',
  path: '/admin/sponsors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsIndexRoute = AdminTeamsIndexRouteImport.update({
  id: '/admin/teams/',
  path: '/admin/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsNewRoute = AdminTeamsNewRouteImport.update({
  id: '/admin/teams/new',
  path: '/admin/teams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVacanciesIndexRoute = AdminVacanciesIndexRouteImport.update({
  id: '/admin/vacancies/',
  path: '/admin/vacancies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVacanciesNewRoute = AdminVacanciesNewRouteImport.update({
  id: '/admin/vacancies/new',
  path: '/admin/vacancies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefRegelsIndexRoute = SportiefRegelsIndexRouteImport.update({
  id: '/sportief/regels/',
  path: '/sportief/regels/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefRegelsIndoorRoute = SportiefRegelsIndoorRouteImport.update({
  id: '/sportief/regels/indoor',
  path: '/sportief/regels/indoor',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefRegelsU10U12Route = SportiefRegelsU10U12RouteImport.update({
  id: '/sportief/regels/u10-u12',
  path: '/sportief/regels/u10-u12',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefRegelsU14PlusRoute = SportiefRegelsU14PlusRouteImport.update({
  id: '/sportief/regels/u14-plus',
  path: '/sportief/regels/u14-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefRegelsU6U8Route = SportiefRegelsU6U8RouteImport.update({
  id: '/sportief/regels/u6-u8',
  path: '/sportief/regels/u6-u8',
  getParentRoute: () => rootRouteImport,
} as any)
const SportiefRegelsU9Route = SportiefRegelsU9RouteImport.update({
  id: '/sportief/regels/u9',
  path: '/sportief/regels/u9',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsEditIdRoute =
  AdminAnnouncementsEditIdRouteImport.update({
    id: '/admin/announcements/edit/$id',
    path: '/admin/announcements/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBoardMembersEditIdRoute = AdminBoardMembersEditIdRouteImport.update({
  id: '/admin/board-members/edit/$id',
  path: '/admin/board-members/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldClosuresEditIdRoute =
  AdminFieldClosuresEditIdRouteImport.update({
    id: '/admin/field-closures/edit/$id',
    path: '/admin/field-closures/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSponsorsEditIdRoute = AdminSponsorsEditIdRouteImport.update({
  id: '/admin/sponsors/edit/$id',
  path: '/admin/sponsors/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsEditIdRoute = AdminTeamsEditIdRouteImport.update({
  id: '/admin/teams/edit/$id',
  path: '/admin/teams/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVacanciesEditIdRoute = AdminVacanciesEditIdRouteImport.update({
  id: '/admin/vacancies/edit/$id',
  path: '/admin/vacancies/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/nieuws': typeof NieuwsRoute
  '/shop': typeof ShopRoute
  '/socials': typeof SocialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/club/bestuur': typeof ClubBestuurRoute
  '/club/geschiedenis': typeof ClubGeschiedenisRoute
  '/club/media': typeof ClubMediaRoute
  '/club/privacy': typeof ClubPrivacyRoute
  '/club/sfeer': typeof ClubSfeerRoute
  '/club/sponsors': typeof ClubSponsorsRoute
  '/club/teams': typeof ClubTeamsRoute
  '/club/veld': typeof ClubVeldRoute
  '/club/veld-status': typeof ClubVeldStatusRoute
  '/club/waarden': typeof ClubWaardenRoute
  '/lidmaatschap/contact': typeof LidmaatschapContactRoute
  '/lidmaatschap/indoor-registratie': typeof LidmaatschapIndoorRegistratieRoute
  '/lidmaatschap/info': typeof LidmaatschapInfoRoute
  '/lidmaatschap/registratie': typeof LidmaatschapRegistratieRoute
  '/lidmaatschap/verzekering': typeof LidmaatschapVerzekeringRoute
  '/sportief/coaches-info': typeof SportiefCoachesInfoRoute
  '/sportief/hockey-principes': typeof SportiefHockeyPrincipesRoute
  '/sportief/hoe-te-spelen': typeof SportiefHoeTeSpelenRoute
  '/sportief/indoor-hockey': typeof SportiefIndoorHockeyRoute
  '/sportief/regels-assistent': typeof SportiefRegelsAssistentRoute
  '/sportief/stick-gids': typeof SportiefStickGidsRoute
  '/sportief/training': typeof SportiefTrainingRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/vacatures/': typeof VacaturesIndexRoute
  '/admin/announcements/new': typeof AdminAnnouncementsNewRoute
  '/admin/board-members/new': typeof AdminBoardMembersNewRoute
  '/admin/field-closures/new': typeof AdminFieldClosuresNewRoute
  '/admin/sponsors/new': typeof AdminSponsorsNewRoute
  '/admin/teams/new': typeof AdminTeamsNewRoute
  '/admin/vacancies/new': typeof AdminVacanciesNewRoute
  '/sportief/regels/indoor': typeof SportiefRegelsIndoorRoute
  '/sportief/regels/u10-u12': typeof SportiefRegelsU10U12Route
  '/sportief/regels/u14-plus': typeof SportiefRegelsU14PlusRoute
  '/sportief/regels/u6-u8': typeof SportiefRegelsU6U8Route
  '/sportief/regels/u9': typeof SportiefRegelsU9Route
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/board-members/': typeof AdminBoardMembersIndexRoute
  '/admin/field-closures/': typeof AdminFieldClosuresIndexRoute
  '/admin/sponsors/': typeof AdminSponsorsIndexRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/vacancies/': typeof AdminVacanciesIndexRoute
  '/sportief/regels/': typeof SportiefRegelsIndexRoute
  '/admin/announcements/edit/$id': typeof AdminAnnouncementsEditIdRoute
  '/admin/board-members/edit/$id': typeof AdminBoardMembersEditIdRoute
  '/admin/field-closures/edit/$id': typeof AdminFieldClosuresEditIdRoute
  '/admin/sponsors/edit/$id': typeof AdminSponsorsEditIdRoute
  '/admin/teams/edit/$id': typeof AdminTeamsEditIdRoute
  '/admin/vacancies/edit/$id': typeof AdminVacanciesEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/nieuws': typeof NieuwsRoute
  '/shop': typeof ShopRoute
  '/socials': typeof SocialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/club/bestuur': typeof ClubBestuurRoute
  '/club/geschiedenis': typeof ClubGeschiedenisRoute
  '/club/media': typeof ClubMediaRoute
  '/club/privacy': typeof ClubPrivacyRoute
  '/club/sfeer': typeof ClubSfeerRoute
  '/club/sponsors': typeof ClubSponsorsRoute
  '/club/teams': typeof ClubTeamsRoute
  '/club/veld': typeof ClubVeldRoute
  '/club/veld-status': typeof ClubVeldStatusRoute
  '/club/waarden': typeof ClubWaardenRoute
  '/lidmaatschap/contact': typeof LidmaatschapContactRoute
  '/lidmaatschap/indoor-registratie': typeof LidmaatschapIndoorRegistratieRoute
  '/lidmaatschap/info': typeof LidmaatschapInfoRoute
  '/lidmaatschap/registratie': typeof LidmaatschapRegistratieRoute
  '/lidmaatschap/verzekering': typeof LidmaatschapVerzekeringRoute
  '/sportief/coaches-info': typeof SportiefCoachesInfoRoute
  '/sportief/hockey-principes': typeof SportiefHockeyPrincipesRoute
  '/sportief/hoe-te-spelen': typeof SportiefHoeTeSpelenRoute
  '/sportief/indoor-hockey': typeof SportiefIndoorHockeyRoute
  '/sportief/regels-assistent': typeof SportiefRegelsAssistentRoute
  '/sportief/stick-gids': typeof SportiefStickGidsRoute
  '/sportief/training': typeof SportiefTrainingRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/vacatures': typeof VacaturesIndexRoute
  '/admin/announcements/new': typeof AdminAnnouncementsNewRoute
  '/admin/board-members/new': typeof AdminBoardMembersNewRoute
  '/admin/field-closures/new': typeof AdminFieldClosuresNewRoute
  '/admin/sponsors/new': typeof AdminSponsorsNewRoute
  '/admin/teams/new': typeof AdminTeamsNewRoute
  '/admin/vacancies/new': typeof AdminVacanciesNewRoute
  '/sportief/regels/indoor': typeof SportiefRegelsIndoorRoute
  '/sportief/regels/u10-u12': typeof SportiefRegelsU10U12Route
  '/sportief/regels/u14-plus': typeof SportiefRegelsU14PlusRoute
  '/sportief/regels/u6-u8': typeof SportiefRegelsU6U8Route
  '/sportief/regels/u9': typeof SportiefRegelsU9Route
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/board-members': typeof AdminBoardMembersIndexRoute
  '/admin/field-closures': typeof AdminFieldClosuresIndexRoute
  '/admin/sponsors': typeof AdminSponsorsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/vacancies': typeof AdminVacanciesIndexRoute
  '/sportief/regels': typeof SportiefRegelsIndexRoute
  '/admin/announcements/edit/$id': typeof AdminAnnouncementsEditIdRoute
  '/admin/board-members/edit/$id': typeof AdminBoardMembersEditIdRoute
  '/admin/field-closures/edit/$id': typeof AdminFieldClosuresEditIdRoute
  '/admin/sponsors/edit/$id': typeof AdminSponsorsEditIdRoute
  '/admin/teams/edit/$id': typeof AdminTeamsEditIdRoute
  '/admin/vacancies/edit/$id': typeof AdminVacanciesEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/nieuws': typeof NieuwsRoute
  '/shop': typeof ShopRoute
  '/socials': typeof SocialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/club/bestuur': typeof ClubBestuurRoute
  '/club/geschiedenis': typeof ClubGeschiedenisRoute
  '/club/media': typeof ClubMediaRoute
  '/club/privacy': typeof ClubPrivacyRoute
  '/club/sfeer': typeof ClubSfeerRoute
  '/club/sponsors': typeof ClubSponsorsRoute
  '/club/teams': typeof ClubTeamsRoute
  '/club/veld': typeof ClubVeldRoute
  '/club/veld-status': typeof ClubVeldStatusRoute
  '/club/waarden': typeof ClubWaardenRoute
  '/lidmaatschap/contact': typeof LidmaatschapContactRoute
  '/lidmaatschap/indoor-registratie': typeof LidmaatschapIndoorRegistratieRoute
  '/lidmaatschap/info': typeof LidmaatschapInfoRoute
  '/lidmaatschap/registratie': typeof LidmaatschapRegistratieRoute
  '/lidmaatschap/verzekering': typeof LidmaatschapVerzekeringRoute
  '/sportief/coaches-info': typeof SportiefCoachesInfoRoute
  '/sportief/hockey-principes': typeof SportiefHockeyPrincipesRoute
  '/sportief/hoe-te-spelen': typeof SportiefHoeTeSpelenRoute
  '/sportief/indoor-hockey': typeof SportiefIndoorHockeyRoute
  '/sportief/regels-assistent': typeof SportiefRegelsAssistentRoute
  '/sportief/stick-gids': typeof SportiefStickGidsRoute
  '/sportief/training': typeof SportiefTrainingRoute
  '/vacatures/$slug': typeof VacaturesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/vacatures/': typeof VacaturesIndexRoute
  '/admin/announcements/new': typeof AdminAnnouncementsNewRoute
  '/admin/board-members/new': typeof AdminBoardMembersNewRoute
  '/admin/field-closures/new': typeof AdminFieldClosuresNewRoute
  '/admin/sponsors/new': typeof AdminSponsorsNewRoute
  '/admin/teams/new': typeof AdminTeamsNewRoute
  '/admin/vacancies/new': typeof AdminVacanciesNewRoute
  '/sportief/regels/indoor': typeof SportiefRegelsIndoorRoute
  '/sportief/regels/u10-u12': typeof SportiefRegelsU10U12Route
  '/sportief/regels/u14-plus': typeof SportiefRegelsU14PlusRoute
  '/sportief/regels/u6-u8': typeof SportiefRegelsU6U8Route
  '/sportief/regels/u9': typeof SportiefRegelsU9Route
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/board-members/': typeof AdminBoardMembersIndexRoute
  '/admin/field-closures/': typeof AdminFieldClosuresIndexRoute
  '/admin/sponsors/': typeof AdminSponsorsIndexRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/vacancies/': typeof AdminVacanciesIndexRoute
  '/sportief/regels/': typeof SportiefRegelsIndexRoute
  '/admin/announcements/edit/$id': typeof AdminAnnouncementsEditIdRoute
  '/admin/board-members/edit/$id': typeof AdminBoardMembersEditIdRoute
  '/admin/field-closures/edit/$id': typeof AdminFieldClosuresEditIdRoute
  '/admin/sponsors/edit/$id': typeof AdminSponsorsEditIdRoute
  '/admin/teams/edit/$id': typeof AdminTeamsEditIdRoute
  '/admin/vacancies/edit/$id': typeof AdminVacanciesEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/events'
    | '/nieuws'
    | '/shop'
    | '/socials'
    | '/admin/users'
    | '/club/bestuur'
    | '/club/geschiedenis'
    | '/club/media'
    | '/club/privacy'
    | '/club/sfeer'
    | '/club/sponsors'
    | '/club/teams'
    | '/club/veld'
    | '/club/veld-status'
    | '/club/waarden'
    | '/lidmaatschap/contact'
    | '/lidmaatschap/indoor-registratie'
    | '/lidmaatschap/info'
    | '/lidmaatschap/registratie'
    | '/lidmaatschap/verzekering'
    | '/sportief/coaches-info'
    | '/sportief/hockey-principes'
    | '/sportief/hoe-te-spelen'
    | '/sportief/indoor-hockey'
    | '/sportief/regels-assistent'
    | '/sportief/stick-gids'
    | '/sportief/training'
    | '/vacatures/$slug'
    | '/admin/'
    | '/vacatures/'
    | '/admin/announcements/new'
    | '/admin/board-members/new'
    | '/admin/field-closures/new'
    | '/admin/sponsors/new'
    | '/admin/teams/new'
    | '/admin/vacancies/new'
    | '/sportief/regels/indoor'
    | '/sportief/regels/u10-u12'
    | '/sportief/regels/u14-plus'
    | '/sportief/regels/u6-u8'
    | '/sportief/regels/u9'
    | '/admin/announcements/'
    | '/admin/board-members/'
    | '/admin/field-closures/'
    | '/admin/sponsors/'
    | '/admin/teams/'
    | '/admin/vacancies/'
    | '/sportief/regels/'
    | '/admin/announcements/edit/$id'
    | '/admin/board-members/edit/$id'
    | '/admin/field-closures/edit/$id'
    | '/admin/sponsors/edit/$id'
    | '/admin/teams/edit/$id'
    | '/admin/vacancies/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/events'
    | '/nieuws'
    | '/shop'
    | '/socials'
    | '/admin/users'
    | '/club/bestuur'
    | '/club/geschiedenis'
    | '/club/media'
    | '/club/privacy'
    | '/club/sfeer'
    | '/club/sponsors'
    | '/club/teams'
    | '/club/veld'
    | '/club/veld-status'
    | '/club/waarden'
    | '/lidmaatschap/contact'
    | '/lidmaatschap/indoor-registratie'
    | '/lidmaatschap/info'
    | '/lidmaatschap/registratie'
    | '/lidmaatschap/verzekering'
    | '/sportief/coaches-info'
    | '/sportief/hockey-principes'
    | '/sportief/hoe-te-spelen'
    | '/sportief/indoor-hockey'
    | '/sportief/regels-assistent'
    | '/sportief/stick-gids'
    | '/sportief/training'
    | '/vacatures/$slug'
    | '/admin'
    | '/vacatures'
    | '/admin/announcements/new'
    | '/admin/board-members/new'
    | '/admin/field-closures/new'
    | '/admin/sponsors/new'
    | '/admin/teams/new'
    | '/admin/vacancies/new'
    | '/sportief/regels/indoor'
    | '/sportief/regels/u10-u12'
    | '/sportief/regels/u14-plus'
    | '/sportief/regels/u6-u8'
    | '/sportief/regels/u9'
    | '/admin/announcements'
    | '/admin/board-members'
    | '/admin/field-closures'
    | '/admin/sponsors'
    | '/admin/teams'
    | '/admin/vacancies'
    | '/sportief/regels'
    | '/admin/announcements/edit/$id'
    | '/admin/board-members/edit/$id'
    | '/admin/field-closures/edit/$id'
    | '/admin/sponsors/edit/$id'
    | '/admin/teams/edit/$id'
    | '/admin/vacancies/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/events'
    | '/nieuws'
    | '/shop'
    | '/socials'
    | '/admin/users'
    | '/club/bestuur'
    | '/club/geschiedenis'
    | '/club/media'
    | '/club/privacy'
    | '/club/sfeer'
    | '/club/sponsors'
    | '/club/teams'
    | '/club/veld'
    | '/club/veld-status'
    | '/club/waarden'
    | '/lidmaatschap/contact'
    | '/lidmaatschap/indoor-registratie'
    | '/lidmaatschap/info'
    | '/lidmaatschap/registratie'
    | '/lidmaatschap/verzekering'
    | '/sportief/coaches-info'
    | '/sportief/hockey-principes'
    | '/sportief/hoe-te-spelen'
    | '/sportief/indoor-hockey'
    | '/sportief/regels-assistent'
    | '/sportief/stick-gids'
    | '/sportief/training'
    | '/vacatures/$slug'
    | '/admin/'
    | '/vacatures/'
    | '/admin/announcements/new'
    | '/admin/board-members/new'
    | '/admin/field-closures/new'
    | '/admin/sponsors/new'
    | '/admin/teams/new'
    | '/admin/vacancies/new'
    | '/sportief/regels/indoor'
    | '/sportief/regels/u10-u12'
    | '/sportief/regels/u14-plus'
    | '/sportief/regels/u6-u8'
    | '/sportief/regels/u9'
    | '/admin/announcements/'
    | '/admin/board-members/'
    | '/admin/field-closures/'
    | '/admin/sponsors/'
    | '/admin/teams/'
    | '/admin/vacancies/'
    | '/sportief/regels/'
    | '/admin/announcements/edit/$id'
    | '/admin/board-members/edit/$id'
    | '/admin/field-closures/edit/$id'
    | '/admin/sponsors/edit/$id'
    | '/admin/teams/edit/$id'
    | '/admin/vacancies/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRoute
  NieuwsRoute: typeof NieuwsRoute
  ShopRoute: typeof ShopRoute
  SocialsRoute: typeof SocialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ClubBestuurRoute: typeof ClubBestuurRoute
  ClubGeschiedenisRoute: typeof ClubGeschiedenisRoute
  ClubMediaRoute: typeof ClubMediaRoute
  ClubPrivacyRoute: typeof ClubPrivacyRoute
  ClubSfeerRoute: typeof ClubSfeerRoute
  ClubSponsorsRoute: typeof ClubSponsorsRoute
  ClubTeamsRoute: typeof ClubTeamsRoute
  ClubVeldRoute: typeof ClubVeldRoute
  ClubVeldStatusRoute: typeof ClubVeldStatusRoute
  ClubWaardenRoute: typeof ClubWaardenRoute
  LidmaatschapContactRoute: typeof LidmaatschapContactRoute
  LidmaatschapIndoorRegistratieRoute: typeof LidmaatschapIndoorRegistratieRoute
  LidmaatschapInfoRoute: typeof LidmaatschapInfoRoute
  LidmaatschapRegistratieRoute: typeof LidmaatschapRegistratieRoute
  LidmaatschapVerzekeringRoute: typeof LidmaatschapVerzekeringRoute
  SportiefCoachesInfoRoute: typeof SportiefCoachesInfoRoute
  SportiefHockeyPrincipesRoute: typeof SportiefHockeyPrincipesRoute
  SportiefHoeTeSpelenRoute: typeof SportiefHoeTeSpelenRoute
  SportiefIndoorHockeyRoute: typeof SportiefIndoorHockeyRoute
  SportiefRegelsAssistentRoute: typeof SportiefRegelsAssistentRoute
  SportiefStickGidsRoute: typeof SportiefStickGidsRoute
  SportiefTrainingRoute: typeof SportiefTrainingRoute
  VacaturesSlugRoute: typeof VacaturesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  VacaturesIndexRoute: typeof VacaturesIndexRoute
  AdminAnnouncementsNewRoute: typeof AdminAnnouncementsNewRoute
  AdminBoardMembersNewRoute: typeof AdminBoardMembersNewRoute
  AdminFieldClosuresNewRoute: typeof AdminFieldClosuresNewRoute
  AdminSponsorsNewRoute: typeof AdminSponsorsNewRoute
  AdminTeamsNewRoute: typeof AdminTeamsNewRoute
  AdminVacanciesNewRoute: typeof AdminVacanciesNewRoute
  SportiefRegelsIndoorRoute: typeof SportiefRegelsIndoorRoute
  SportiefRegelsU10U12Route: typeof SportiefRegelsU10U12Route
  SportiefRegelsU14PlusRoute: typeof SportiefRegelsU14PlusRoute
  SportiefRegelsU6U8Route: typeof SportiefRegelsU6U8Route
  SportiefRegelsU9Route: typeof SportiefRegelsU9Route
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
  AdminBoardMembersIndexRoute: typeof AdminBoardMembersIndexRoute
  AdminFieldClosuresIndexRoute: typeof AdminFieldClosuresIndexRoute
  AdminSponsorsIndexRoute: typeof AdminSponsorsIndexRoute
  AdminTeamsIndexRoute: typeof AdminTeamsIndexRoute
  AdminVacanciesIndexRoute: typeof AdminVacanciesIndexRoute
  SportiefRegelsIndexRoute: typeof SportiefRegelsIndexRoute
  AdminAnnouncementsEditIdRoute: typeof AdminAnnouncementsEditIdRoute
  AdminBoardMembersEditIdRoute: typeof AdminBoardMembersEditIdRoute
  AdminFieldClosuresEditIdRoute: typeof AdminFieldClosuresEditIdRoute
  AdminSponsorsEditIdRoute: typeof AdminSponsorsEditIdRoute
  AdminTeamsEditIdRoute: typeof AdminTeamsEditIdRoute
  AdminVacanciesEditIdRoute: typeof AdminVacanciesEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nieuws': {
      id: '/nieuws'
      path: '/nieuws'
      fullPath: '/nieuws'
      preLoaderRoute: typeof NieuwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socials': {
      id: '/socials'
      path: '/socials'
      fullPath: '/socials'
      preLoaderRoute: typeof SocialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/bestuur': {
      id: '/club/bestuur'
      path: '/club/bestuur'
      fullPath: '/club/bestuur'
      preLoaderRoute: typeof ClubBestuurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/geschiedenis': {
      id: '/club/geschiedenis'
      path: '/club/geschiedenis'
      fullPath: '/club/geschiedenis'
      preLoaderRoute: typeof ClubGeschiedenisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/media': {
      id: '/club/media'
      path: '/club/media'
      fullPath: '/club/media'
      preLoaderRoute: typeof ClubMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/privacy': {
      id: '/club/privacy'
      path: '/club/privacy'
      fullPath: '/club/privacy'
      preLoaderRoute: typeof ClubPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/sfeer': {
      id: '/club/sfeer'
      path: '/club/sfeer'
      fullPath: '/club/sfeer'
      preLoaderRoute: typeof ClubSfeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/sponsors': {
      id: '/club/sponsors'
      path: '/club/sponsors'
      fullPath: '/club/sponsors'
      preLoaderRoute: typeof ClubSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/teams': {
      id: '/club/teams'
      path: '/club/teams'
      fullPath: '/club/teams'
      preLoaderRoute: typeof ClubTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/veld': {
      id: '/club/veld'
      path: '/club/veld'
      fullPath: '/club/veld'
      preLoaderRoute: typeof ClubVeldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/veld-status': {
      id: '/club/veld-status'
      path: '/club/veld-status'
      fullPath: '/club/veld-status'
      preLoaderRoute: typeof ClubVeldStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/waarden': {
      id: '/club/waarden'
      path: '/club/waarden'
      fullPath: '/club/waarden'
      preLoaderRoute: typeof ClubWaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidmaatschap/contact': {
      id: '/lidmaatschap/contact'
      path: '/lidmaatschap/contact'
      fullPath: '/lidmaatschap/contact'
      preLoaderRoute: typeof LidmaatschapContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidmaatschap/indoor-registratie': {
      id: '/lidmaatschap/indoor-registratie'
      path: '/lidmaatschap/indoor-registratie'
      fullPath: '/lidmaatschap/indoor-registratie'
      preLoaderRoute: typeof LidmaatschapIndoorRegistratieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidmaatschap/info': {
      id: '/lidmaatschap/info'
      path: '/lidmaatschap/info'
      fullPath: '/lidmaatschap/info'
      preLoaderRoute: typeof LidmaatschapInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidmaatschap/registratie': {
      id: '/lidmaatschap/registratie'
      path: '/lidmaatschap/registratie'
      fullPath: '/lidmaatschap/registratie'
      preLoaderRoute: typeof LidmaatschapRegistratieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidmaatschap/verzekering': {
      id: '/lidmaatschap/verzekering'
      path: '/lidmaatschap/verzekering'
      fullPath: '/lidmaatschap/verzekering'
      preLoaderRoute: typeof LidmaatschapVerzekeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/coaches-info': {
      id: '/sportief/coaches-info'
      path: '/sportief/coaches-info'
      fullPath: '/sportief/coaches-info'
      preLoaderRoute: typeof SportiefCoachesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/hockey-principes': {
      id: '/sportief/hockey-principes'
      path: '/sportief/hockey-principes'
      fullPath: '/sportief/hockey-principes'
      preLoaderRoute: typeof SportiefHockeyPrincipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/hoe-te-spelen': {
      id: '/sportief/hoe-te-spelen'
      path: '/sportief/hoe-te-spelen'
      fullPath: '/sportief/hoe-te-spelen'
      preLoaderRoute: typeof SportiefHoeTeSpelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/indoor-hockey': {
      id: '/sportief/indoor-hockey'
      path: '/sportief/indoor-hockey'
      fullPath: '/sportief/indoor-hockey'
      preLoaderRoute: typeof SportiefIndoorHockeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/regels-assistent': {
      id: '/sportief/regels-assistent'
      path: '/sportief/regels-assistent'
      fullPath: '/sportief/regels-assistent'
      preLoaderRoute: typeof SportiefRegelsAssistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/stick-gids': {
      id: '/sportief/stick-gids'
      path: '/sportief/stick-gids'
      fullPath: '/sportief/stick-gids'
      preLoaderRoute: typeof SportiefStickGidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/training': {
      id: '/sportief/training'
      path: '/sportief/training'
      fullPath: '/sportief/training'
      preLoaderRoute: typeof SportiefTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacatures/': {
      id: '/vacatures/'
      path: '/vacatures'
      fullPath: '/vacatures/'
      preLoaderRoute: typeof VacaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacatures/$slug': {
      id: '/vacatures/$slug'
      path: '/vacatures/$slug'
      fullPath: '/vacatures/$slug'
      preLoaderRoute: typeof VacaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements/': {
      id: '/admin/announcements/'
      path: '/admin/announcements'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements/new': {
      id: '/admin/announcements/new'
      path: '/admin/announcements/new'
      fullPath: '/admin/announcements/new'
      preLoaderRoute: typeof AdminAnnouncementsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/board-members/': {
      id: '/admin/board-members/'
      path: '/admin/board-members'
      fullPath: '/admin/board-members/'
      preLoaderRoute: typeof AdminBoardMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/board-members/new': {
      id: '/admin/board-members/new'
      path: '/admin/board-members/new'
      fullPath: '/admin/board-members/new'
      preLoaderRoute: typeof AdminBoardMembersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/field-closures/': {
      id: '/admin/field-closures/'
      path: '/admin/field-closures'
      fullPath: '/admin/field-closures/'
      preLoaderRoute: typeof AdminFieldClosuresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/field-closures/new': {
      id: '/admin/field-closures/new'
      path: '/admin/field-closures/new'
      fullPath: '/admin/field-closures/new'
      preLoaderRoute: typeof AdminFieldClosuresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors/': {
      id: '/admin/sponsors/'
      path: '/admin/sponsors'
      fullPath: '/admin/sponsors/'
      preLoaderRoute: typeof AdminSponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors/new': {
      id: '/admin/sponsors/new'
      path: '/admin/sponsors/new'
      fullPath: '/admin/sponsors/new'
      preLoaderRoute: typeof AdminSponsorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/': {
      id: '/admin/teams/'
      path: '/admin/teams'
      fullPath: '/admin/teams/'
      preLoaderRoute: typeof AdminTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/new': {
      id: '/admin/teams/new'
      path: '/admin/teams/new'
      fullPath: '/admin/teams/new'
      preLoaderRoute: typeof AdminTeamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vacancies/': {
      id: '/admin/vacancies/'
      path: '/admin/vacancies'
      fullPath: '/admin/vacancies/'
      preLoaderRoute: typeof AdminVacanciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vacancies/new': {
      id: '/admin/vacancies/new'
      path: '/admin/vacancies/new'
      fullPath: '/admin/vacancies/new'
      preLoaderRoute: typeof AdminVacanciesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/regels/': {
      id: '/sportief/regels/'
      path: '/sportief/regels'
      fullPath: '/sportief/regels/'
      preLoaderRoute: typeof SportiefRegelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/regels/indoor': {
      id: '/sportief/regels/indoor'
      path: '/sportief/regels/indoor'
      fullPath: '/sportief/regels/indoor'
      preLoaderRoute: typeof SportiefRegelsIndoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/regels/u10-u12': {
      id: '/sportief/regels/u10-u12'
      path: '/sportief/regels/u10-u12'
      fullPath: '/sportief/regels/u10-u12'
      preLoaderRoute: typeof SportiefRegelsU10U12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/regels/u14-plus': {
      id: '/sportief/regels/u14-plus'
      path: '/sportief/regels/u14-plus'
      fullPath: '/sportief/regels/u14-plus'
      preLoaderRoute: typeof SportiefRegelsU14PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/regels/u6-u8': {
      id: '/sportief/regels/u6-u8'
      path: '/sportief/regels/u6-u8'
      fullPath: '/sportief/regels/u6-u8'
      preLoaderRoute: typeof SportiefRegelsU6U8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sportief/regels/u9': {
      id: '/sportief/regels/u9'
      path: '/sportief/regels/u9'
      fullPath: '/sportief/regels/u9'
      preLoaderRoute: typeof SportiefRegelsU9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements/edit/$id': {
      id: '/admin/announcements/edit/$id'
      path: '/admin/announcements/edit/$id'
      fullPath: '/admin/announcements/edit/$id'
      preLoaderRoute: typeof AdminAnnouncementsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/board-members/edit/$id': {
      id: '/admin/board-members/edit/$id'
      path: '/admin/board-members/edit/$id'
      fullPath: '/admin/board-members/edit/$id'
      preLoaderRoute: typeof AdminBoardMembersEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/field-closures/edit/$id': {
      id: '/admin/field-closures/edit/$id'
      path: '/admin/field-closures/edit/$id'
      fullPath: '/admin/field-closures/edit/$id'
      preLoaderRoute: typeof AdminFieldClosuresEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors/edit/$id': {
      id: '/admin/sponsors/edit/$id'
      path: '/admin/sponsors/edit/$id'
      fullPath: '/admin/sponsors/edit/$id'
      preLoaderRoute: typeof AdminSponsorsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/edit/$id': {
      id: '/admin/teams/edit/$id'
      path: '/admin/teams/edit/$id'
      fullPath: '/admin/teams/edit/$id'
      preLoaderRoute: typeof AdminTeamsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vacancies/edit/$id': {
      id: '/admin/vacancies/edit/$id'
      path: '/admin/vacancies/edit/$id'
      fullPath: '/admin/vacancies/edit/$id'
      preLoaderRoute: typeof AdminVacanciesEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRoute,
  NieuwsRoute: NieuwsRoute,
  ShopRoute: ShopRoute,
  SocialsRoute: SocialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ClubBestuurRoute: ClubBestuurRoute,
  ClubGeschiedenisRoute: ClubGeschiedenisRoute,
  ClubMediaRoute: ClubMediaRoute,
  ClubPrivacyRoute: ClubPrivacyRoute,
  ClubSfeerRoute: ClubSfeerRoute,
  ClubSponsorsRoute: ClubSponsorsRoute,
  ClubTeamsRoute: ClubTeamsRoute,
  ClubVeldRoute: ClubVeldRoute,
  ClubVeldStatusRoute: ClubVeldStatusRoute,
  ClubWaardenRoute: ClubWaardenRoute,
  LidmaatschapContactRoute: LidmaatschapContactRoute,
  LidmaatschapIndoorRegistratieRoute: LidmaatschapIndoorRegistratieRoute,
  LidmaatschapInfoRoute: LidmaatschapInfoRoute,
  LidmaatschapRegistratieRoute: LidmaatschapRegistratieRoute,
  LidmaatschapVerzekeringRoute: LidmaatschapVerzekeringRoute,
  SportiefCoachesInfoRoute: SportiefCoachesInfoRoute,
  SportiefHockeyPrincipesRoute: SportiefHockeyPrincipesRoute,
  SportiefHoeTeSpelenRoute: SportiefHoeTeSpelenRoute,
  SportiefIndoorHockeyRoute: SportiefIndoorHockeyRoute,
  SportiefRegelsAssistentRoute: SportiefRegelsAssistentRoute,
  SportiefStickGidsRoute: SportiefStickGidsRoute,
  SportiefTrainingRoute: SportiefTrainingRoute,
  VacaturesSlugRoute: VacaturesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  VacaturesIndexRoute: VacaturesIndexRoute,
  AdminAnnouncementsNewRoute: AdminAnnouncementsNewRoute,
  AdminBoardMembersNewRoute: AdminBoardMembersNewRoute,
  AdminFieldClosuresNewRoute: AdminFieldClosuresNewRoute,
  AdminSponsorsNewRoute: AdminSponsorsNewRoute,
  AdminTeamsNewRoute: AdminTeamsNewRoute,
  AdminVacanciesNewRoute: AdminVacanciesNewRoute,
  SportiefRegelsIndoorRoute: SportiefRegelsIndoorRoute,
  SportiefRegelsU10U12Route: SportiefRegelsU10U12Route,
  SportiefRegelsU14PlusRoute: SportiefRegelsU14PlusRoute,
  SportiefRegelsU6U8Route: SportiefRegelsU6U8Route,
  SportiefRegelsU9Route: SportiefRegelsU9Route,
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
  AdminBoardMembersIndexRoute: AdminBoardMembersIndexRoute,
  AdminFieldClosuresIndexRoute: AdminFieldClosuresIndexRoute,
  AdminSponsorsIndexRoute: AdminSponsorsIndexRoute,
  AdminTeamsIndexRoute: AdminTeamsIndexRoute,
  AdminVacanciesIndexRoute: AdminVacanciesIndexRoute,
  SportiefRegelsIndexRoute: SportiefRegelsIndexRoute,
  AdminAnnouncementsEditIdRoute: AdminAnnouncementsEditIdRoute,
  AdminBoardMembersEditIdRoute: AdminBoardMembersEditIdRoute,
  AdminFieldClosuresEditIdRoute: AdminFieldClosuresEditIdRoute,
  AdminSponsorsEditIdRoute: AdminSponsorsEditIdRoute,
  AdminTeamsEditIdRoute: AdminTeamsEditIdRoute,
  AdminVacanciesEditIdRoute: AdminVacanciesEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
