on:
  pull_request:
    types: [closed]         # fire when PR is closed
    branches: [main]        # only PRs targeting main

jobs:
  gui-tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build and serve
        run: |
          npm run build
          npx http-server dist &
          npx wait-on http://localhost:8080
          
      - name: Run GUI tests
        run: npm run test:gui

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

